name: Publish on Modrinth
run-name: Deployed by ${{ github.actor}}.
on:
  workflow_dispatch:
    inputs:
      version:
        description: Mod Version
        required: true
      minecraft_version:
        description: Minecraft Version
        required: true
      yarn_mappings:
        description: Yarn Mappings
        required: true
      loader_version:
        description: Loader Version
        required: true
      fabric_version:
        description: Fabric API Version
        required: true
      modmenu_version:
        description: Mod Menu Version
        required: true

env:
  JAVA_VERSION: 17
  MODRINTH_TOKEN: ${{secrets.MODRINTH_TOKEN}}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: "temurin"
          java-version: "${{env.JAVA_VERSION}}"

      - name: Set Environment Variables from Inputs
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "MINECRAFT_VERSION=${{ inputs.minecraft_version }}" >> $GITHUB_ENV
          echo "YARN_MAPPINGS=${{ inputs.yarn_mappings }}" >> $GITHUB_ENV
          echo "LOADER_VERSION=${{ inputs.loader_version }}" >> $GITHUB_ENV
          echo "FABRIC_VERSION=${{ inputs.fabric_version }}" >> $GITHUB_ENV
          echo "MODMENU_VERSION=${{ inputs.modmenu_version }}" >> $GITHUB_ENV

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          name: ""
          version: "${{inputs.version}}"
          version-type: release
          changelog-file: CHANGELOG.md
          java: "${{env.JAVA_VERSION}}"
          
