name: Publish on Modrinth
run-name: Deployed by ${{ github.actor }} - ${{ inputs.version }} on ${{ inputs.minecraft_version }}.
on:
  workflow_dispatch:
    inputs:
      version:
        description: Mod Version
        required: true
      minecraft_version:
        description: Minecraft Version
        required: true
      yarn_mappings:
        description: Yarn Mappings
        required: true
      loader_version:
        description: Loader Version
        required: true
      fabric_version:
        description: Fabric API Version
        required: true
      modmenu_version:
        description: Mod Menu Version
        required: true

env:
  JAVA_VERSION: 17
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: "temurin"
          java-version: "${{ env.JAVA_VERSION }}"

      - name: Overwrite gradle.properties
        run: |
          cat gradle.properties
          
          sed -i 's/version=.*/version=${{ inputs.version }}/' gradle.properties
          sed -i 's/minecraft_version=.*/minecraft_version=${{ inputs.minecraft_version }}/' gradle.properties
          sed -i 's/yarn_mappings=.*/yarn_mappings=${{ inputs.yarn_mappings }}/' gradle.properties
          sed -i 's/loader_version=.*/loader_version=${{ inputs.loader_version }}/' gradle.properties
          sed -i 's/fabric_version=.*/fabric_version=${{ inputs.fabric_version }}/' gradle.properties
          sed -i 's/modmenu_version=.*/modmenu_version=${{ inputs.modmenu_version }}/' gradle.properties

          cat gradle.properties

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-token: "${{ env.MODRINTH_TOKEN }}"

          name: "Inventive Inventory ${{ inputs.version }}"
          version: "${{ inputs.version }}"
          version-type: release
          changelog-file: CHANGELOG.md
          java: "${{ env.JAVA_VERSION }}"
          
